import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'fr' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'hero.title': 'Just Do It',
    'hero.subtitle': 'Discover the latest athletic gear and elevate your performance',
    'hero.cta': 'Shop Now',
    'products.title': 'Featured Products',
    'product.addToCart': 'Add to Cart',
    'cart.title': 'Shopping Cart',
    'checkout.title': 'Checkout',
    'checkout.name': 'Full Name',
    'checkout.email': 'Email Address',
    'checkout.phone': 'Phone Number',
    'checkout.address': 'Shipping Address',
  'checkout.city': 'City',
  'checkout.cityPlaceholder': 'Select a city',
  'checkout.citySelectLabel': 'City',
    'checkout.complete': 'Complete Purchase',
    'success.title': 'Purchase Successful!',
    'success.message': 'Thank you for your order. You will receive a confirmation email shortly.',
    'success.continue': 'Continue Shopping',
    'theme.toggle': 'Toggle Theme',
    'language.select': 'Language',
    'about.heroTitle': 'Our Story',
    'about.heroText': 'We set out to build a destination where performance, style, and innovation meet. Every product we curate is chosen to help you push harder, recover better, and feel proud of your progress.',
    'about.missionTitle': 'Our Mission',
    'about.missionText': 'To empower athletes and everyday movers with gear that elevates performance while honoring sustainability and design.',
    'about.visionTitle': 'Our Vision',
    'about.visionText': 'Becoming the most trusted modern athletic marketplace—where innovation, inclusion, and accountability drive progress.',
    'about.valuesTitle': 'Core Values',
    'about.value.quality.title': 'Quality First',
    'about.value.quality.desc': 'Premium gear tested for performance and durability.',
    'about.value.trust.title': 'Trust',
    'about.value.trust.desc': 'Transparent policies and reliable customer support.',
    'about.value.community.title': 'Community',
    'about.value.community.desc': 'We grow alongside athletes at every level.',
    'about.value.sustainability.title': 'Sustainability',
    'about.value.sustainability.desc': 'Eco-conscious sourcing and packaging choices.',
    'about.milestonesTitle': 'Milestones',
    'about.milestone.founded': 'Started with a vision to modernize athletic retail.',
    'about.milestone.1k': 'Reached our first thousand happy athletes.',
    'about.milestone.expansion': 'Introduced accessories and training equipment.',
    'about.milestone.sustainability': 'Moved to 60% recyclable packaging.',
    'about.teamTitle': 'Team',
    'about.ctaTitle': 'Ready to Level Up?',
    'about.ctaText': 'Explore our latest performance drops or reach out for personalized gear guidance tailored to your training goals.',
    'cta.shopProducts': 'Shop Products',
    'cta.contactUs': 'Contact Us',
    'products.pageTitle': 'Our Products',
    'products.searchPlaceholder': 'Search products...',
    'products.sort.default': 'Sort: Default',
    'products.sort.priceAsc': 'Price ↑',
    'products.sort.priceDesc': 'Price ↓',
    'products.sort.nameAsc': 'Name A-Z',
    'products.sort.nameDesc': 'Name Z-A',
    'products.reset': 'Reset',
    'products.empty': 'No products match your filters.',
    'products.clearFilters': 'Clear Filters',
    'contact.title': 'Get in Touch',
    'contact.address': 'Address',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.hours': 'Hours',
    'contact.quickHelpTitle': 'Need Quick Help?',
    'contact.quickHelpText': 'Check our FAQ or email us anytime. We usually respond within 24 hours.',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Subject',
    'contact.form.reason': 'Reason',
    'contact.form.message': 'Message',
    'contact.form.placeholder.subject': 'Order question, product feedback...',
    'contact.reason.general': 'General Inquiry',
    'contact.reason.order': 'Order Status',
    'contact.reason.product': 'Product Question',
    'contact.reason.feedback': 'Feedback',
    'contact.reason.support': 'Support',
    'contact.submit': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.sendingStatus': 'Submitting your message...',
    'contact.sentToastTitle': 'Message Sent',
    'contact.sentToastDesc': 'We will get back to you shortly.',
    'contact.error.name': 'Name is required',
    'contact.error.email': 'Valid email required',
    'contact.error.message': 'Message must be at least 20 characters',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.products': 'Produits',
    'nav.about': 'À propos',
    'nav.contact': 'Contact',
    'hero.title': 'Just Do It',
    'hero.subtitle': 'Découvrez les derniers équipements sportifs et améliorez vos performances',
    'hero.cta': 'Acheter maintenant',
    'products.title': 'Produits vedettes',
    'product.addToCart': 'Ajouter au panier',
    'cart.title': 'Panier d\'achats',
    'checkout.title': 'Commande',
    'checkout.name': 'Nom complet',
    'checkout.email': 'Adresse e-mail',
    'checkout.phone': 'Numéro de téléphone',
    'checkout.address': 'Adresse de livraison',
  'checkout.city': 'Ville',
  'checkout.cityPlaceholder': 'Sélectionnez une ville',
  'checkout.citySelectLabel': 'Ville',
    'checkout.complete': 'Finaliser l\'achat',
    'success.title': 'Achat réussi!',
    'success.message': 'Merci pour votre commande. Vous recevrez un e-mail de confirmation sous peu.',
    'success.continue': 'Continuer les achats',
    'theme.toggle': 'Changer de thème',
    'language.select': 'Langue',
    'about.heroTitle': 'Notre histoire',
    'about.heroText': 'Nous avons créé une destination où performance, style et innovation se rencontrent. Chaque produit est choisi pour vous aider à aller plus loin, récupérer mieux et être fier de vos progrès.',
    'about.missionTitle': 'Notre mission',
    'about.missionText': 'Donner aux athlètes et aux personnes actives des équipements qui améliorent la performance tout en respectant la durabilité et le design.',
    'about.visionTitle': 'Notre vision',
    'about.visionText': 'Devenir la place de marché sportive moderne la plus fiable—où innovation, inclusion et responsabilité stimulent le progrès.',
    'about.valuesTitle': 'Valeurs clés',
    'about.value.quality.title': 'Qualité d’abord',
    'about.value.quality.desc': 'Équipement premium testé pour la performance et la durabilité.',
    'about.value.trust.title': 'Confiance',
    'about.value.trust.desc': 'Politiques transparentes et support fiable.',
    'about.value.community.title': 'Communauté',
    'about.value.community.desc': 'Nous grandissons aux côtés des athlètes de tous niveaux.',
    'about.value.sustainability.title': 'Durabilité',
    'about.value.sustainability.desc': 'Approvisionnement et emballages écoresponsables.',
    'about.milestonesTitle': 'Étapes clés',
    'about.milestone.founded': 'Démarré avec la vision de moderniser le commerce sportif.',
    'about.milestone.1k': 'Atteint notre premier millier de clients satisfaits.',
    'about.milestone.expansion': 'Ajout d’accessoires et d’équipements d’entraînement.',
    'about.milestone.sustainability': 'Passé à 60% d’emballages recyclables.',
    'about.teamTitle': 'Équipe',
    'about.ctaTitle': 'Prêt à monter de niveau ?',
    'about.ctaText': 'Découvrez nos dernières nouveautés ou contactez-nous pour des conseils personnalisés adaptés à vos objectifs.',
    'cta.shopProducts': 'Voir les produits',
    'cta.contactUs': 'Contactez-nous',
    'products.pageTitle': 'Nos produits',
    'products.searchPlaceholder': 'Rechercher des produits...',
    'products.sort.default': 'Tri : Défaut',
    'products.sort.priceAsc': 'Prix ↑',
    'products.sort.priceDesc': 'Prix ↓',
    'products.sort.nameAsc': 'Nom A-Z',
    'products.sort.nameDesc': 'Nom Z-A',
    'products.reset': 'Réinitialiser',
    'products.empty': 'Aucun produit ne correspond à vos filtres.',
    'products.clearFilters': 'Effacer les filtres',
    'contact.title': 'Contactez-nous',
    'contact.address': 'Adresse',
    'contact.phone': 'Téléphone',
    'contact.email': 'E-mail',
    'contact.hours': 'Horaires',
    'contact.quickHelpTitle': 'Besoin d’aide rapide ?',
    'contact.quickHelpText': 'Consultez notre FAQ ou écrivez-nous. Réponse sous 24h en général.',
    'contact.form.name': 'Nom',
    'contact.form.email': 'E-mail',
    'contact.form.subject': 'Sujet',
    'contact.form.reason': 'Motif',
    'contact.form.message': 'Message',
    'contact.form.placeholder.subject': 'Question commande, retour produit...',
    'contact.reason.general': 'Demande générale',
    'contact.reason.order': 'Suivi de commande',
    'contact.reason.product': 'Question produit',
    'contact.reason.feedback': 'Retour',
    'contact.reason.support': 'Assistance',
    'contact.submit': 'Envoyer',
    'contact.sending': 'Envoi...',
    'contact.sendingStatus': 'Envoi de votre message...',
    'contact.sentToastTitle': 'Message envoyé',
    'contact.sentToastDesc': 'Nous reviendrons vers vous sous peu.',
    'contact.error.name': 'Le nom est requis',
    'contact.error.email': 'E-mail valide requis',
    'contact.error.message': 'Le message doit contenir au moins 20 caractères',
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.products': 'المنتجات',
    'nav.about': 'حول',
    'nav.contact': 'اتصل بنا',
    'hero.title': 'Just Do It',
    'hero.subtitle': 'اكتشف أحدث المعدات الرياضية وارتقِ بأدائك',
    'hero.cta': 'تسوق الآن',
    'products.title': 'المنتجات المميزة',
    'product.addToCart': 'أضف إلى السلة',
    'cart.title': 'عربة التسوق',
    'checkout.title': 'إتمام الطلب',
    'checkout.name': 'الاسم الكامل',
    'checkout.email': 'عنوان البريد الإلكتروني',
    'checkout.phone': 'رقم الهاتف',
    'checkout.address': 'عنوان الشحن',
  'checkout.city': 'المدينة',
  'checkout.cityPlaceholder': 'اختر مدينة',
  'checkout.citySelectLabel': 'المدينة',
    'checkout.complete': 'إتمام الشراء',
    'success.title': 'تم الشراء بنجاح!',
    'success.message': 'شكراً لك على طلبك. ستتلقى بريداً إلكترونياً للتأكيد قريباً.',
    'success.continue': 'متابعة التسوق',
    'theme.toggle': 'تبديل المظهر',
    'language.select': 'اللغة',
    'about.heroTitle': 'قصتنا',
    'about.heroText': 'أنشأنا وجهة يلتقي فيها الأداء والأناقة والابتكار. كل منتج نختاره يساعدك على التقدم والتعافي والشعور بالفخر بإنجازاتك.',
    'about.missionTitle': 'مهمتنا',
    'about.missionText': 'تمكين الرياضيين وكل من يتحرك يومياً بمعدات تعزز الأداء مع الاهتمام بالاستدامة والتصميم.',
    'about.visionTitle': 'رؤيتنا',
    'about.visionText': 'أن نصبح السوق الرياضي الحديث الأكثر ثقة حيث يقود الابتكار والشمولية والمسؤولية التقدم.',
    'about.valuesTitle': 'القيم الأساسية',
    'about.value.quality.title': 'الجودة أولاً',
    'about.value.quality.desc': 'معدات متميزة مُختبرة للأداء والمتانة.',
    'about.value.trust.title': 'الثقة',
    'about.value.trust.desc': 'سياسات شفافة ودعم موثوق.',
    'about.value.community.title': 'المجتمع',
    'about.value.community.desc': 'ننمو جنباً إلى جنب مع الرياضيين في كل المستويات.',
    'about.value.sustainability.title': 'الاستدامة',
    'about.value.sustainability.desc': 'اختيارات توريد وتغليف صديقة للبيئة.',
    'about.milestonesTitle': 'محطات مهمة',
    'about.milestone.founded': 'بدأنا برؤية لتحديث تجارة التجزئة الرياضية.',
    'about.milestone.1k': 'حققنا أول ألف عميل سعيد.',
    'about.milestone.expansion': 'قدمنا الإكسسوارات ومعدات التدريب.',
    'about.milestone.sustainability': 'انتقلنا إلى تغليف قابل لإعادة التدوير بنسبة 60٪.',
    'about.teamTitle': 'الفريق',
    'about.ctaTitle': 'هل أنت مستعد للارتقاء؟',
    'about.ctaText': 'استكشف أحدث منتجاتنا أو تواصل للحصول على إرشاد مخصص يناسب أهدافك.',
    'cta.shopProducts': 'تسوق المنتجات',
    'cta.contactUs': 'اتصل بنا',
    'products.pageTitle': 'منتجاتنا',
    'products.searchPlaceholder': 'ابحث عن منتجات...',
    'products.sort.default': 'الفرز: الافتراضي',
    'products.sort.priceAsc': 'السعر ↑',
    'products.sort.priceDesc': 'السعر ↓',
    'products.sort.nameAsc': 'الاسم A-Z',
    'products.sort.nameDesc': 'الاسم Z-A',
    'products.reset': 'إعادة تعيين',
    'products.empty': 'لا توجد منتجات تطابق المرشحات.',
    'products.clearFilters': 'مسح المرشحات',
    'contact.title': 'تواصل معنا',
    'contact.address': 'العنوان',
    'contact.phone': 'الهاتف',
    'contact.email': 'البريد الإلكتروني',
    'contact.hours': 'الساعات',
    'contact.quickHelpTitle': 'هل تحتاج مساعدة سريعة؟',
    'contact.quickHelpText': 'اطلع على الأسئلة الشائعة أو راسلنا في أي وقت. عادةً نرد خلال 24 ساعة.',
    'contact.form.name': 'الاسم',
    'contact.form.email': 'البريد الإلكتروني',
    'contact.form.subject': 'الموضوع',
    'contact.form.reason': 'السبب',
    'contact.form.message': 'الرسالة',
    'contact.form.placeholder.subject': 'سؤال عن طلب، ملاحظات المنتج...',
    'contact.reason.general': 'استفسار عام',
    'contact.reason.order': 'حالة الطلب',
    'contact.reason.product': 'سؤال عن منتج',
    'contact.reason.feedback': 'ملاحظات',
    'contact.reason.support': 'دعم',
    'contact.submit': 'إرسال الرسالة',
    'contact.sending': 'جارٍ الإرسال...',
    'contact.sendingStatus': 'يتم إرسال رسالتك...',
    'contact.sentToastTitle': 'تم إرسال الرسالة',
    'contact.sentToastDesc': 'سنتواصل معك قريباً.',
    'contact.error.name': 'الاسم مطلوب',
    'contact.error.email': 'بريد إلكتروني صالح مطلوب',
    'contact.error.message': 'يجب أن تكون الرسالة 20 حرفاً على الأقل',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  React.useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}